---
apiVersion: v1
kind: Namespace
metadata:
  name: cron

---
apiVersion: batch/v1
kind:	CronJob
metadata: 
  name: cron-demo
  namespace: cron
spec:
  schedule: "0 23 * * *"
  jobTemplate:
    metadata: 
      name: cronjob
      namespace: cron
    spec:
      backoffLimit: 0
      template:
        metadata:
          name: cron-pod
          namespace: cron
          labels:
            app: nginx
        spec:
          restartPolicy: OnFailure
          containers:
            - image: alpine
              name: cron-con
              command: 
                - apk add wget
                - wget https://dockerimages1.s3.ap-south-1.amazonaws.com/spring-petclinic-3.2.0-SNAPSHOT.jar
