---
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  initContainers:
    - image: alpine
      name: init1
      command: 
        - sleep 
        - "30"
    - image: alpine
      name: init2
      command:
        - sleep
        - "30"
  containers:
    - image: nginx
      name: nginx-con
      ports:
        - containerPort: 80
          protocol: TCP
