---
apiVersion: v1
kind: Pod
metadata:
  name: activity2-pod
spec:
  containers:
    - image: nginx
      name: nginx-container
      ports:
        - containerPort: 80
          protocol: TCP
    - image: jenkins/jenkins
      name: jenkins-containers
      ports:
        - containerPort: 8080
          protocol: TCP