---
apiVersion: v1
kind: Pod
metadata:
  name: node-selector
spec:
  nodeSelector:
    beta.kubernetes.io/os: linux
  containers:
    - image: nginx:1.23
      name: nginx-container
      ports:
        - containerPort: 80
  