---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: gp2  
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: sql-pod
spec:
  containers:
    - image: mysql:8.0.36-debian
      name: mysql-con
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: emp
        - name: MYSQL_USER
          value: bhanu
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_BHANU_PASSWORD
          value: bhanu
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: vol
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: vol-pvc
        readOnly: false