apiVersion: v1
kind: ReplicationController
metadata:
  name: rcpod
spec:
  minReadySeconds: 5
  replicas: 5
  selector: 
    app: nginx
  template:
    metadata:
      name: nginz-pod
      labels:
        app: nginx
        ver: "1"
    spec:
      containers:
        - image: nginx
          name: nginx-con
          ports: 
            - containerPort: 80
              protocol: TCP