apiVersion: v1
kind: Service
metadata:
  name: nginx-serv
spec:
  type: ClusterIP
  selector: 
    app: nginx
    ver: "1"
  ports:
    - name: nginx-serv-network
      targetPort: 80
      port: 3501