apiVersion: v1
kind: Service
metadata:
  name: node-srv
spec:
  type: nodeport
  selector: 
    app: nginx
    ver: "1"
  ports:
    - name: NodePort-network
      port: 3500
      targetPort: 80
      nodePort: 30555