apiVersion: v1 
kind: Pod
metadata:
  name: taint-pod
spec:
  containers:
    - image: nginx
      name: taint-con
      ports:
        - containerPort: 80
  tolerations:
    - key: poc
      value: "true"
      operator: Equal

#kubectl taint nodes <node-name> poc=true:NoSchedule
#for other nodes kubectl taint nodes <node-name> poc=false:NoSchedule
#Ensure all the nodes are tainted and then apply