apiVersion: v1
kind: Pod
metadata:
  name: mount-pod
spec:
  containers:
    - image: alpine
      name: mount-con
      command:
        - sleep
        - infinity
      volumeMounts:
        - name: vol
          mountPath: /config
  volumes:
    - name: vol
      configMap:
        name: test-config