apiVersion: v1
kind: Pod
metadata:
  name: env-pod
spec:
  containers:
    - image: alpine
      name: env-con
      command:
        - sleep
        - infinity
      envFrom:
        - configMapRef:
            name: test-config