apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jen-dp
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchLabels:
      app: jen
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: jen-pod
      labels:
        app: jen
        ver: "1"
    spec:
      containers:
        - image: nginx:mainline-alpine-slim
          name: jen-con
          ports: 
            - containerPort: 8080
              protocol: TCP

